[package]
name = "web-pages"
version = "0.1.0"
edition = "2024"

[dependencies]
clorinde = { version = "0.0.0", path = "../clorinde" }
daisy_rsx = "0.1.50"
dioxus = { version = "0.6", default-features = false, features = ["macro", "html", "signals"] }
dioxus-ssr = { version = "0.6", default-features = false }
web-assets = { version = "0.1.0", path = "../web-assets" }
